map = "mapa base
X,X,X,X,X,X,X,X,X,X,X,X,X
X,X,X,X,X,A,A,A,X,X,X,X,X
X,X,X,X,X,X,A,X,X,X,X,X,X
X,A,A,A,A,X,A,X,A,A,A,A,X
X,A,A,A,A,X,A,X,A,A,A,A,X
A,X,X,X,X,X,X,X,X,X,X,X,X
A,X,A,A,X,A,A,A,X,A,A,X,A
A,A,X,A,X,A,A,A,X,A,X,A,A
A,A,X,X,X,X,X,X,X,X,X,A,A
X,X,A,A,A,A,A,A,A,A,X,X,X
X,X,A,A,A,A,A,A,A,A,A,X,X
X,A,A,A,X,X,A,X,X,A,A,A,X
X,X,A,A,X,A,A,A,X,A,A,X,X
X,X,X,X,X,A,A,A,X,X,X,X,X
X,X,X,X,X,X,X,X,X,X,X,X,X
X,X,X,X,X,X,X,X,X,X,X,X,X
X,X,X,X,X,X,X,X,X,X,X,X,X
X,X,X,X,X,X,X,X,X,X,X,X,X"